# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

__all__ = [
    "load_npy",
    "load_npz",
    "NpzFile",
]
from collections.abc import Iterator, Mapping
from typing import Any, TypeAlias

import numpy as np
from numpy.typing import NDArray

# Importing `spdl.io.lib` instead of `spdl.io.lilb._archive`
# so as to delay the import of C++ extension module
from . import lib as _libspdl

Buffer: TypeAlias = "bytes | bytearray | memoryview[bytes]"

_NpzEntry: TypeAlias = "tuple[int, int, int, int] | tuple[int, int, int, int, int]"
_DEFAULT_MAX_UNCOMPRESSED_BYTES = 1 << 30


def _get_pointer(data: Buffer) -> int:
    return np.frombuffer(data, dtype=np.byte).ctypes.data


class _OwnedArrayInterface:
    """Expose the array interface of ``obj`` while keeping ``owner`` alive.

    The ``NPYArray`` object returned by the C++ extension points at a memory
    region it does not own. NumPy sets the ``base`` of an array to the object it
    was created from, so creating the array from this wrapper (instead of from
    the ``NPYArray`` directly) keeps the object owning the memory alive for as
    long as the array is.
    """

    def __init__(self, obj: object, owner: Buffer) -> None:
        self._obj = obj
        self._owner = owner
        self._readonly = memoryview(owner).readonly

    @property
    def __array_interface__(self) -> dict[str, Any]:
        # pyre-ignore[16]
        interface = dict(self._obj.__array_interface__)
        pointer, _ = interface["data"]
        interface["data"] = (pointer, self._readonly)
        return interface


def load_npy(data: Buffer, *, copy: bool = False) -> NDArray:
    """Load NumPy NDArray from bytes.

    This function loads NumPy NDArray from memory. It is equivalent to
    ``numpy.load(io.BytesIO(data))``, but it is more efficient.

    .. note::

       This function does not support ``object``, structured, or record dtypes.

    Example:

        >>> ref = np.arange(20)
        >>> buffer = BytesIO()
        >>> np.save(buffer, ref)
        >>> buffer.seek(0)
        >>> data = buffer.getvalue()
        >>> restore = spdl.io.load_npy(data)
        >>> assert np.array_equal(restore, ref)

    Args:
        data: The data generated by :py:func:`numpy.save` function.
            (Note that it is different from :py:meth:`numpy.ndarray.tobytes`,
            which does not contain shape and dtype.)
        copy: Whether to copy data. With the default ``False``, the returned
            array is a view and inherits the source buffer's writability.
            Passing ``True`` returns an independent, writable array.

    Returns:
        The restored array data.

    .. versionchanged:: 0.7.0

       Zero-copy arrays now retain their source buffer and are read-only when
       that source is read-only. A resizable source cannot be resized while a
       returned zero-copy array is alive. Pass ``copy=True`` when a writable,
       independently resizable array is required. Fortran-contiguous arrays now expose their
       column-major strides correctly. Malformed shape or dtype metadata and
       truncated payloads are now rejected instead of constructing an invalid
       array view.

    .. seealso::

       - :py:mod:`numpy.lib.format`: The detail of NPY serialization is found.

       - `_read_array_header
         <https://github.com/numpy/numpy/blob/v2.2.0/numpy/lib/format.py#L604>`_:
         The function called by :py:func:`numpy.load` to parse the header.
       - `_read_array <https://github.com/numpy/numpy/blob/v2.2.0/numpy/lib/format.py#L762>`_:
         The function called by :py:func:`numpy.load` when loading the data region of NPY file.

    .. note::

       There is a branch in
       `_read_array <https://github.com/numpy/numpy/blob/v2.2.0/numpy/lib/format.py#L827-L854>`_
       function where the execution can call some faster implementation.
       However, :py:class:`~io.BytesIO` does not meet the condition.
       (:py:func:`~numpy.lib.format.isfileobj` returns ``False`` for
       :py:class:`io.BytesIO`.
       [`source <https://github.com/numpy/numpy/blob/v2.2.0/numpy/lib/format.py#L999>`_])
       Even if the execution takes the faster :py:func:`numpy.fromfile` path, it
       `creates a new array
       <https://github.com/numpy/numpy/blob/v2.2.0/numpy/_core/records.py#L935-L939>`_.

    """
    owner: "memoryview[bytes]" = memoryview(data)
    buffer = _libspdl._archive.load_npy(_get_pointer(owner), owner.nbytes)
    return np.array(_OwnedArrayInterface(buffer, owner), copy=copy)


class NpzFile(Mapping):
    """NpzFile()
    A class mimics the behavior of :py:class:`numpy.lib.npyio.NpzFile`.

    It is a thin wrapper around a zip archive, and implements
    :py:class:`collections.abc.Mapping` interface.

    See :py:func:`load_npz` for the usage.

    Args:
        data: The archive data to load.
        meta: Metadata describing each archive entry.
        max_uncompressed_bytes: Maximum cumulative declared uncompressed size
            of DEFLATE-compressed entries. Defaults to 1 GiB.

    .. versionadded:: 0.7.0

       The ``max_uncompressed_bytes`` argument.
    """

    def __init__(
        self,
        data: Buffer,
        meta: "Mapping[str, _NpzEntry]",
        *,
        max_uncompressed_bytes: int = _DEFAULT_MAX_UNCOMPRESSED_BYTES,
    ) -> None:
        # `_data` is a raw pointer into `data`, so the archive must be kept
        # alive. A memoryview also blocks resizing a mutable source, which
        # would reallocate the buffer and leave `_data` dangling.
        self._buf: "memoryview[bytes]" = memoryview(data)
        self._data: int = _get_pointer(self._buf)
        self._len: int = self._buf.nbytes

        # `NpzFile` is part of the public API, so callers can construct it with
        # metadata that did not come from the bounds-checked ZIP parser. Check
        # every borrowed region before it reaches the raw-pointer C++ API and
        # snapshot the dictionary so later caller mutation cannot bypass the
        # validation.
        if max_uncompressed_bytes < 0:
            raise ValueError("max_uncompressed_bytes must be non-negative.")

        validated_meta: dict[str, tuple[int, int, int, int, int | None]] = {}
        total_uncompressed_bytes = 0
        for name, entry in meta.items():
            if len(entry) == 4:
                offset, compressed_size, uncompressed_size, compression_method = entry
                crc32 = None
            elif len(entry) == 5:
                (
                    offset,
                    compressed_size,
                    uncompressed_size,
                    compression_method,
                    crc32,
                ) = entry
            else:
                raise ValueError(
                    f"NPZ entry {name!r} metadata must contain 4 or 5 fields."
                )
            if offset < 0 or compressed_size < 0:
                raise ValueError(f"NPZ entry {name!r} has a negative payload region.")
            if offset > self._len or compressed_size > self._len - offset:
                raise ValueError(
                    f"NPZ entry {name!r} payload is outside the archive buffer."
                )
            if uncompressed_size < 0:
                raise ValueError(
                    f"NPZ entry {name!r} has a negative uncompressed size."
                )
            if compression_method == 0:
                # Stored entries are borrowed directly from the already-bounded
                # archive buffer, so they cannot expand or consume a separate
                # decompression allocation budget.
                if compressed_size != uncompressed_size:
                    raise ValueError(
                        f"NPZ stored entry {name!r} must have matching compressed "
                        "and uncompressed sizes."
                    )
            elif compression_method == 8:
                if (
                    uncompressed_size
                    > max_uncompressed_bytes - total_uncompressed_bytes
                ):
                    raise ValueError(
                        "NPZ deflated entries exceed max_uncompressed_bytes "
                        f"({max_uncompressed_bytes})."
                    )
                total_uncompressed_bytes += uncompressed_size
            else:
                raise ValueError(
                    f"NPZ entry {name!r} uses unsupported compression method "
                    f"{compression_method}."
                )
            validated_meta[name] = (
                offset,
                compressed_size,
                uncompressed_size,
                compression_method,
                crc32,
            )

        self._meta = validated_meta
        self.files: list[str] = [f.removesuffix(".npy") for f in validated_meta]

    def __iter__(self) -> Iterator[str]:
        return iter(self.files)

    def __len__(self) -> int:
        return len(self.files)

    def __getitem__(self, key: str) -> NDArray:
        """Provide dictionary-like access to array data.

        One difference from the regular dictionary access is that
        it also supports accessing the item without ``.npy`` suffix
        in the key. This matches the behavior of :py:class:`numpy.lib.npyio.NpzFile`.
        """
        if key in self._meta:
            pass
        elif key in self.files:
            key = f"{key}.npy"
        else:
            raise KeyError(f"{key} is not a file in the archive")

        (
            offset,
            compressed_size,
            uncompressed_size,
            compression_method,
            crc32,
        ) = self._meta[key]
        match compression_method:
            case 0:
                # The data is stored uncompressed, so the resulting array refers
                # to the archive itself. It must keep the archive alive, as it
                # can outlive this `NpzFile` object.
                buffer = _libspdl._archive.load_npy(
                    self._data,
                    size=compressed_size,
                    offset=offset,
                    crc32=crc32,
                )
                return np.array(_OwnedArrayInterface(buffer, self._buf), copy=False)
            case 8:
                # The data is inflated into a buffer owned by the `NPYArray`
                # object, which NumPy keeps alive as the base of the array.
                buffer = _libspdl._archive.load_npy_compressed(
                    self._data,
                    offset,
                    compressed_size,
                    uncompressed_size,
                    crc32,
                )
                return np.array(buffer, copy=False)
            case _:
                raise ValueError(
                    "Compression method other than DEFLATE is not supported."
                )

    def __contains__(self, key: str) -> bool:  # pyre-ignore[14]
        return key in self._meta or key in self.files

    def __repr__(self) -> str:
        return f"NpzFile object with {len(self)} entries."


def load_npz(
    data: Buffer,
    *,
    max_uncompressed_bytes: int = _DEFAULT_MAX_UNCOMPRESSED_BYTES,
) -> NpzFile:
    """**[Experimental]** Load a numpy archive file (``npz``).

    It is almost a drop-in replacement for :py:func:`numpy.load` function,
    but it only supports the basic use cases.

    This function uses the C++ implementation of the zip archive reader, which
    releases the GIL. So it is more efficient than the official NumPy implementation
    for supported cases.

    Args:
        data: The data to load.
        max_uncompressed_bytes: Maximum cumulative declared uncompressed size
            of DEFLATE-compressed entries. Defaults to 1 GiB. Increase this
            explicitly only for trusted archives that require more space.

    .. versionadded:: 0.7.0

       The ``max_uncompressed_bytes`` argument.

    .. versionchanged:: 0.7.0

       Arrays backed by stored entries now inherit the source buffer's
       writability. Arrays inflated from compressed entries own writable
       storage independently of the source archive.

    Example

       >>> x = np.arange(10)
       >>> y = np.sin(x)
       >>>
       >>> with tempfile.TemporaryFile() as f:
       ...     np.savez(f, x=x, y=y)
       ...     f.seek(0)
       ...     data = spdl.io.load_npz(f.read())
       ...
       >>> assert np.array_equal(data["x"], x)
       >>> assert np.array_equal(data["y"], y)

    """
    mv = memoryview(data)
    meta = {val[0]: val[1:] for val in _libspdl._archive.parse_zip(mv)}
    return NpzFile(
        data,
        meta,
        max_uncompressed_bytes=max_uncompressed_bytes,
    )
