site_name: SPDL Documentation

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - inline-svg
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 3
            separate_signature: true
            show_object_full_path: true
            show_root_heading: true
            show_bases: false
            show_source: false
            preload_modules:
              - spdl.io
              - spdl.dataset
              - spdl.dataloader
              - spdl.utils
            members_order: source
            extensions:
            - docs/resolver.py:SPDLDynamicResolver:
          import:
          - https://pytorch.org/docs/master/objects.inv

  - mkdoxy:
      projects:
        libspdl:
          src-dirs: src/libspdl
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h"
            RECURSIVE: YES
            SEPARATE_MEMBER_PAGES: YES
            EXCLUDE_SYMBOLS: std,spdl::core::detail,folly
            PREDEFINED: SPDL_USE_CUDA SPDL_USE_NVCODEC
            SOURCE_BROWSER: YES
            VERBATIM_HEADERS: NO

nav:
  - "SPDL (Python)":
      - Installation: installation.md
      - "spdl.io":
          - "Overview": spdl/io/overview.md
          - "Low-level APIs":
              - "Overview": spdl/io/core/about.md
              - "Demuxing": spdl/io/core/demuxing.md
              - "Decoding": spdl/io/core/decoding.md
              - "Conversion": spdl/io/core/conversion.md
          - "High-level APIs":
              - "Loading Media": spdl/io/api/load.md
              - "Saving Media": spdl/io/api/encoding.md
          - "Preprocessing": spdl/io/preprocessing.md
          - "Support Structures":
            - "Packets": spdl/io/support/packets.md
            - "Frames": spdl/io/support/frames.md
            - "Buffer": spdl/io/support/buffer.md
            - "Config": spdl/io/support/config.md
            - "Thread Pool": spdl/io/support/thread_pool.md
            - "Others": spdl/io/support/others.md
      - "spdl.dataset (Experimental)":
          - "DataSet": spdl/dataset/dataset.md
          - "ImageNet": spdl/dataset/imagenet.md
          - "Kinetics": spdl/dataset/kinetics.md
          - "LibriSpeech": spdl/dataset/librispeech.md
      - "spdl.dataloader (Experimental)":
          - "Task Execution": spdl/dataloader/dataloader.md
      - "spdl.utils":
          - "Tracing": spdl/utils/tracing.md
          - "Folly": spdl/utils/folly.md
          - "FFmpeg": spdl/utils/ffmpeg.md
          - "Futures": spdl/utils/futures.md
          - "Misc": spdl/utils/misc.md
  - "LibSPDL (C++)":
      - Links: libspdl/links.md
      - Classes:
          - "Class List": "libspdl/annotated.md"
          - "Class Index": "libspdl/classes.md"
          - "Class Hierarchy": "libspdl/hierarchy.md"
          - "Class Members": "libspdl/class_members.md"
          - "Class Member Functions": "libspdl/class_member_functions.md"
          - "Class Member Variables": "libspdl/class_member_variables.md"
          - "Class Member Typedefs": "libspdl/class_member_typedefs.md"
          - "Class Member Enumerations": "libspdl/class_member_enums.md"
      - Namespaces:
          - "Namespace List": "libspdl/namespaces.md"
          - "Namespace Members": "libspdl/namespace_members.md"
          - "Namespace Member Functions": "libspdl/namespace_member_functions.md"
          - "Namespace Member Variables": "libspdl/namespace_member_variables.md"
          - "Namespace Member Typedefs": "libspdl/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "libspdl/namespace_member_enums.md"
      - Functions: "libspdl/functions.md"
      - Variables: "libspdl/variables.md"
      - Macros: "libspdl/macros.md"
      - Files: "libspdl/files.md"
      - Pages: "libspdl/pages.md"
  - "Development Note":
      - "Design Principles":
          - "Understanding I/O Bottleneck": "dev_notes/bottleneck.md"
          - "Design Principles of LibSPDL": "dev_notes/spdl_design.md"
      - "dev_notes/structure_of_packets_and_frames.md"
      - "dev_notes/async.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
