extend-exclude = [
  "setup.py",
  "docs/source",
  "third_party",
  "src/spdl/io/lib/_libspdl.pyi",
  "src/spdl/io/lib/_libspdl_cuda.pyi",
  "src/spdl/io/lib/_archive.pyi",
]

[lint]
extend-select = [
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "I",    # isort
  "PGH",  # pygrep-hooks
  "RUF",  # Ruff-specific
  "T20",  # flake8-print
]

# Note: These settings are picked to match meta-internal linting
[lint.isort]
case-sensitive = false
combine-as-imports = true
default-section = "first-party"
order-by-type = false

[lint.per-file-ignores]
"tests/**" = ["T20"]
"examples/**" = ["T20"]
