package:
  name: spdl
  version: "{{ environ.get('SPDL_BUILD_VERSION', '0.0.0') }}"

source:
  path: "../.."

requirements:
  build:
    # NOTE on osx:
    # Ideally, we use the compiler tool chain provided by Anaconda, but
    # they do not provide clang v15 currently.
    # https://anaconda.org/anaconda/clangxx
    # So, we use the system compiler provided by GitHub Action.
    - {{ compiler('c') }} # [not osx]
    - {{ compiler('cxx') }} # [not osx]

  host:
    - python
    - setuptools
    - cmake
    - ninja
    - typing_extensions
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}

  run:
    - python
    - numpy
    {{ environ.get('CONDA_CUDARUNTIME_CONSTRAINT', '') }}

build:
  string: py{{py}}_{{ environ.get('CU_VERSION', 'cpu') }}
  script_env:
    - SPDL_USE_CUDA
    - SPDL_USE_NVCODEC
    - SPDL_USE_NVJPEG
    - SPDL_LINK_STATIC_NVJPEG
    - SPDL_USE_NPPI
    - SPDL_USE_TRACING
    - SPDL_BUILD_STUB

test:
  imports:
    - spdl.io
    - spdl.utils
    - spdl.dataloader
    - spdl.pipeline

  source_files:
    - tests/spdl_unittest

  requires:
    - pytest
    - numpy

about:
  home: https://github.com/facebookresearch/spdl
  summary: Scalable and performant data loading for scientific computing
