# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.


from collections.abc import Iterator
from typing import overload


def parse_zip(arg: bytes, /) -> list[tuple[str, int, int, int, int]]: ...

class NPYArray:
    @property
    def __array_interface__(self) -> dict: ...

def load_npy(data: int, size: int, offset: int = 0) -> NPYArray: ...

def load_npy_compressed(data: int, offset: int, compressed_size: int, uncompressed_size: int) -> NPYArray: ...

class InMemoryTarParser:
    def __iter__(self) -> Iterator[tuple[str, int, int]]: ...

@overload
def parse_tar(arg: bytes, /) -> InMemoryTarParser: ...

@overload
def parse_tar(arg: object, /) -> FileObjectTarParser: ...

class FileObjectTarParser:
    def __iter__(self) -> Iterator[tuple]: ...
