

def parse_zip(arg: bytes, /) -> list[tuple[str, int, int, int, int]]: ...

class NPYArray:
    @property
    def __array_interface__(self) -> dict: ...

def load_npy(data: int, size: int, offset: int = 0) -> NPYArray: ...

def load_npy_compressed(data: int, offset: int, compressed_size: int, uncompressed_size: int) -> NPYArray: ...
