# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.


from collections.abc import Callable, Sequence
from typing import Annotated, overload

from numpy.typing import ArrayLike

import spdl.io.lib._libspdl


class CUDAConfig:
    """
    Specify the CUDA device and memory management.

    See the factory function :py:func:`~spdl.io.cuda_config`.
    """

def cuda_config(device_index: int, stream: int = 2, allocator: tuple[Callable[[int, int, int], int], Callable[[int], None]] | None = None) -> CUDAConfig: ...

class CUDABuffer:
    """
    CUDABuffer implements CUDA array interface.

    To be passed to casting functions like :py:func:`~spdl.io.to_torch` and
    :py:func:`~spdl.io.to_numba`.
    """

    @property
    def __cuda_array_interface__(self) -> dict:
        """
        See https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html.
        """

    @property
    def device_index(self) -> int:
        """The device index."""

class NvDecDecoder:
    """
    Decodes video packets using NVDEC hardware acceleration.

    Use :py:func:`nvdec_decoder` to instantiate.

    This decoder supports two decoding workflows:

    1. **Batch decoding** - Decode all packets at once:

       .. code-block:: python

          decoder = spdl.io.nvdec_decoder(cuda_config, codec)
          nv12_buffer = decoder.decode_packets(packets)
          rgb = spdl.io.nv12_to_rgb(nv12_buffer, cuda_config)
          # Buffer shape: [num_frames, height*1.5, width]

    2. **Streaming decoding** - Process packets incrementally with batched output:

       .. code-block:: python

          decoder = spdl.io.nvdec_decoder(cuda_config, codec)
          decoder.init_buffer(num_frames)  # Initialize frame buffer

          for packets in packet_stream:
              for batch in decoder.streaming_decode_packets(packets):
                  # batch is CUDABuffer with shape [num_frames, h*1.5, w]
                  rgb = spdl.io.nv12_to_rgb(batch, cuda_config)
                  # Process rgb frames

          # Flush and get remaining frames
          for batch in decoder.flush():
              rgb = spdl.io.nv12_to_rgb(batch, cuda_config)
              # Process final frames

    .. note::

       To decode H264 and HEVC videos, packets must be in Annex B format.
       Use :py:func:`~spdl.io.apply_bsf` to convert:

       .. code-block:: python

          if codec.name in ("h264", "hevc"):
              packets = spdl.io.apply_bsf(packets, f"{codec.name}_mp4toannexb")

    .. seealso::

       - :py:func:`decode_packets_nvdec`: Decode video packets using NVDEC
       - :py:func:`streaming_load_video_nvdec`: Decode video frames in streaming fashion
       - :py:mod:`streaming_nvdec_decoding`: Tutorial for streaming video decode
    """

    def init_decoder(self, device_config: CUDAConfig, codec: spdl.io.lib._libspdl.VideoCodec, *, crop_left: int = 0, crop_top: int = 0, crop_right: int = 0, crop_bottom: int = 0, scale_width: int = -1, scale_height: int = -1) -> None:
        """
        Initialize the decoder.

        .. versionchanged:: 0.2.0

           This method was renamed from ``init()``.

        .. deprecated:: 0.1.7

           This method was merged with :py:func:`nvdec_decoder()`.
           Pass these parameters directly to initialize the decoder.
           The old pattern of calling ``decoder.init()`` after ``nvdec_decoder()``
           will be removed in a future version.

        .. note::

           Creation of underlying decoder object is expensive.
           Typically, it takes about 300ms or more.

           To mitigate this the implementation tries to reuse the decoder.
           This works if the new video uses the same codecs as
           the previous one, and the difference is limited to the
           resolution of the video.

           If you are processing videos of different codecs, then the
           decoder has to be re-created.

        Args:
            cuda_config: The device configuration. Specifies the GPU of which
                video decoder chip is used, the CUDA memory allocator and
                CUDA stream used to fetch the result from the decoder engine.

            codec: The information of the source video.

            crop_left, crop_top, crop_right, crop_bottom (int):
                *Optional:* Crop the given number of pixels from each side.

            scale_width, scale_height (int): *Optional:* Resize the frame.
                Resizing is applied after cropping.
        """

    def decode_packets(self, packets: spdl.io.lib._libspdl.VideoPackets) -> CUDABuffer:
        """
        Decode all packets and return NV12 buffer.

        This method decodes all packets and flushes the decoder in one operation,
        and returns the resulting frames as one contiguous memory buffer.

        Args:
            packets: Video packets to decode.

        Returns:
            A :py:class:`~spdl.io.CUDABuffer` containing NV12 frames with shape
            ``[num_frames, h*1.5, width]``, where ``num_frames`` reflects
            the actual number of decoded frames, which should match
            the number of packets.
        """

    def init_buffer(self, num_frames: int) -> None:
        """
        Initialize frame buffer for streaming decode.

        This must be called before using :py:meth:`streaming_decode_packets` for streaming decode.

        Args:
            num_frames: The number of frames per batch.
        """

    def flush(self) -> CUDABufferIterator:
        """
        Flush the decoder and yield remaining batches.

        Call this method at the end of video stream to flush the decoder
        and retrieve any remaining buffered frames as batches.

        Returns:
            Iterator that yields remaining CUDABuffer batches in NV12 format.
        """

    def streaming_decode_packets(self, packets: spdl.io.lib._libspdl.VideoPackets) -> CUDABufferIterator:
        """
        Streaming decode packets and yield batches.

        This method decodes packets and yields batches of frames as they become ready.
        The frame buffer must be initialized with init_buffer() before calling this.

        Args:
            packets: Video packets to decode.

        Returns:
            Iterator that yields CUDABuffer batches in NV12 format.
        """

class CUDABufferIterator:
    def __iter__(self) -> CUDABufferIterator: ...

    def __next__(self) -> CUDABuffer: ...

@overload
def decode_image_nvjpeg(data: bytes, *, device_config: CUDAConfig, scale_width: int = -1, scale_height: int = -1, pix_fmt: str = 'rgb', sync: bool = True, _zero_clear: bool = False) -> CUDABuffer: ...

@overload
def decode_image_nvjpeg(data: Sequence[bytes], *, device_config: CUDAConfig, scale_width: int, scale_height: int, pix_fmt: str = 'rgb', sync: bool = True, _zero_clear: bool = False) -> CUDABuffer: ...

def cpu_storage(size: int) -> spdl.io.lib._libspdl.CPUStorage: ...

@overload
def transfer_buffer(buffer: spdl.io.lib._libspdl.CPUBuffer, *, device_config: CUDAConfig) -> CUDABuffer: ...

@overload
def transfer_buffer(buffer: Annotated[ArrayLike, dict(order='C', device='cpu')], *, device_config: CUDAConfig) -> CUDABuffer: ...

def transfer_buffer_cpu(buffer: Annotated[ArrayLike, dict(order='C', device='cuda')]) -> spdl.io.lib._libspdl.CPUBuffer: ...

def init() -> None: ...

def built_with_cuda() -> bool: ...

def built_with_nvcodec() -> bool: ...

def built_with_nvjpeg() -> bool: ...

def synchronize_stream(arg: CUDAConfig, /) -> None: ...

def nv12_to_planar_rgb(buffer: CUDABuffer, *, device_config: CUDAConfig, matrix_coeff: int = 1, sync: bool = True) -> CUDABuffer:
    """
    Convert batched NV12 frames to planar RGB.

    Args:
        buffer: 3D buffer with shape ``[num_frames, height*1.5, width]``.
        device_config: The CUDA device configuration.
        matrix_coeff: Color matrix coefficients for conversion (default: ``BT.709``).
        sync: If ``True``, synchronizes the stream before returning.

    Returns:
        CUDA buffer containing planar RGB data with shape ``[num_frames, 3, height, width]``.
    """

def nv12_to_planar_bgr(buffer: CUDABuffer, *, device_config: CUDAConfig, matrix_coeff: int = 1, sync: bool = True) -> CUDABuffer:
    """
    Convert batched NV12 frames to planar BGR.

    Args:
        buffer: 3D buffer with shape ``[num_frames, height*1.5, width]``.
        device_config: The CUDA device configuration.
        matrix_coeff: Color matrix coefficients for conversion (default: ``BT.709``).
        sync: If ``True``, synchronizes the stream before returning.

    Returns:
        CUDA buffer containing planar BGR data with shape ``[num_frames, 3, height, width]``.
    """
