# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.


from collections.abc import Callable, Sequence
from typing import Annotated, overload

from numpy.typing import ArrayLike

import spdl.io.lib._libspdl


class CUDAConfig:
    """
    Specify the CUDA device and memory management.

    See the factory function :py:func:`~spdl.io.cuda_config`.
    """

def cuda_config(device_index: int, stream: int = 0, allocator: tuple[Callable[[int, int, int], int], Callable[[int], None]] | None = None) -> CUDAConfig: ...

class CUDABuffer:
    """
    CUDABuffer implements CUDA array interface.

    To be passed to casting functions like :py:func:`~spdl.io.to_torch` and
    :py:func:`~spdl.io.to_numba`.
    """

    @property
    def __cuda_array_interface__(self) -> dict:
        """
        See https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html.
        """

    @property
    def device_index(self) -> int:
        """The device index."""

class NvDecDecoder:
    def reset(self) -> None: ...

    def init(self, device_config: CUDAConfig, codec: spdl.io.lib._libspdl.VideoCodec, *, crop_left: int = 0, crop_top: int = 0, crop_right: int = 0, crop_bottom: int = 0, scale_width: int = -1, scale_height: int = -1) -> None: ...

    def decode(self, packets: spdl.io.lib._libspdl.VideoPackets) -> list[CUDABuffer]: ...

    def flush(self) -> list[CUDABuffer]: ...

@overload
def decode_image_nvjpeg(data: bytes, *, device_config: CUDAConfig, scale_width: int = -1, scale_height: int = -1, pix_fmt: str = 'rgb', _zero_clear: bool = False) -> CUDABuffer: ...

@overload
def decode_image_nvjpeg(data: Sequence[bytes], *, device_config: CUDAConfig, scale_width: int, scale_height: int, pix_fmt: str = 'rgb', _zero_clear: bool = False) -> CUDABuffer: ...

def cpu_storage(size: int) -> spdl.io.lib._libspdl.CPUStorage: ...

@overload
def transfer_buffer(buffer: spdl.io.lib._libspdl.CPUBuffer, *, device_config: CUDAConfig) -> CUDABuffer: ...

@overload
def transfer_buffer(buffer: Annotated[ArrayLike, dict(order='C', device='cpu')], *, device_config: CUDAConfig) -> CUDABuffer: ...

def transfer_buffer_cpu(buffer: Annotated[ArrayLike, dict(order='C', device='cuda')]) -> spdl.io.lib._libspdl.CPUBuffer: ...

def init() -> None: ...

def built_with_cuda() -> bool: ...

def built_with_nvcodec() -> bool: ...

def built_with_nvjpeg() -> bool: ...

def synchronize_stream(arg: CUDAConfig, /) -> None: ...

def nv12_to_planar_rgb(buffers: Sequence[CUDABuffer], *, device_config: CUDAConfig, matrix_coeff: int = 1) -> CUDABuffer: ...

def nv12_to_planar_bgr(buffers: Sequence[CUDABuffer], *, device_config: CUDAConfig, matrix_coeff: int = 1) -> CUDABuffer: ...
