# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.


from collections.abc import Callable, Sequence
from typing import Annotated, overload

from numpy.typing import NDArray

import spdl.io.lib._spdl_ffmpeg8


class CUDAConfig:
    pass

def cuda_config(device_index: int, stream: int = 0, allocator: tuple[Callable[[int, int, int], int], Callable[[int], None]] | None = None) -> CUDAConfig: ...

class CUDABuffer:
    @property
    def __cuda_array_interface__(self) -> None: ...

    @property
    def device_index(self) -> None: ...

class NvDecDecoder:
    def reset(self) -> None: ...

    def init(self, device_config: CUDAConfig, codec: spdl.io.lib._spdl_ffmpeg8.VideoCodec, *, crop_left: int = 0, crop_top: int = 0, crop_right: int = 0, crop_bottom: int = 0, scale_width: int = -1, scale_height: int = -1) -> None: ...

    def decode(self, packets: spdl.io.lib._spdl_ffmpeg8.VideoPackets) -> list[CUDABuffer]: ...

    def flush(self) -> list[CUDABuffer]: ...

@overload
def decode_image_nvjpeg(data: bytes, *, device_config: CUDAConfig, scale_width: int = -1, scale_height: int = -1, pix_fmt: str = 'rgb', _zero_clear: bool = False) -> None: ...

@overload
def decode_image_nvjpeg(data: Sequence[bytes], *, device_config: CUDAConfig, scale_width: int, scale_height: int, pix_fmt: str = 'rgb', _zero_clear: bool = False) -> None: ...

def cpu_storage(size: int) -> spdl.io.lib._spdl_ffmpeg8.CPUStorage: ...

@overload
def transfer_buffer(buffer: spdl.io.lib._spdl_ffmpeg8.CPUBuffer, *, device_config: CUDAConfig) -> None: ...

@overload
def transfer_buffer(buffer: Annotated[NDArray, dict(order='C', device='cpu')], *, device_config: CUDAConfig) -> None: ...

def transfer_buffer_cpu(buffer: Annotated[NDArray, dict(order='C', device='cuda')]) -> None: ...

def init() -> None: ...

def built_with_cuda() -> bool: ...

def built_with_nvcodec() -> bool: ...

def built_with_nvjpeg() -> bool: ...

def synchronize_stream(arg: object, /) -> None: ...

def nv12_to_planar_rgb(buffers: object, *, device_config: CUDAConfig, matrix_coeff: int = 1) -> CUDABuffer: ...

def nv12_to_planar_bgr(buffers: object, *, device_config: CUDAConfig, matrix_coeff: int = 1) -> CUDABuffer: ...
