# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.




class WAVHeader:
    """WAV file header information."""

    @property
    def audio_format(self) -> int:
        """Audio format code (1=PCM, 3=IEEE float, etc.)"""

    @property
    def num_channels(self) -> int:
        """Number of audio channels"""

    @property
    def sample_rate(self) -> int:
        """Sample rate in Hz"""

    @property
    def byte_rate(self) -> int:
        """Byte rate (sample_rate * num_channels * bits_per_sample / 8)"""

    @property
    def block_align(self) -> int:
        """Block alignment (num_channels * bits_per_sample / 8)"""

    @property
    def bits_per_sample(self) -> int:
        """Bits per sample"""

    @property
    def data_size(self) -> int:
        """Size of audio data in bytes"""

def load_wav(data: bytes, *, time_offset_seconds: float | None = None, duration_seconds: float | None = None) -> dict:
    """
    Extract audio samples from WAV data.

    Args:
        wav_data: Binary WAV data as bytes or string
        time_offset_seconds: Optional starting time in seconds (default: 0.0)
        duration_seconds: Optional duration in seconds (default: until end)

    Returns:
        dict: Dictionary compliant with Array Interface Protocol containing:
            - version: Protocol version (3)
            - shape: Tuple of (num_samples, num_channels)
            - typestr: Data type string
            - data: Tuple of (data_pointer, read_only_flag)
            - owner: Object owning the data buffer

    Raises:
        WAVParseError: If the WAV data is invalid or time range is out of bounds
    """

def parse_wav(data: bytes) -> WAVHeader:
    """
    Parse WAV file header and extract metadata.

    Args:
        data: Binary WAV data as bytes

    Returns:
        WAVHeader: Object containing WAV header information with attributes:
            - audio_format: Audio format code (1=PCM, 3=IEEE float, etc.)
            - num_channels: Number of audio channels
            - sample_rate: Sample rate in Hz
            - byte_rate: Byte rate (sample_rate * num_channels * bits_per_sample / 8)
            - block_align: Block alignment (num_channels * bits_per_sample / 8)
            - bits_per_sample: Bits per sample
            - data_size: Size of audio data in bytes

    Raises:
        WAVParseError: If the WAV data is invalid or malformed
    """
