# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# pyre-ignore-all-errors
#
# @generated
# This file is generated by stubgen.py
# and should not be edited manually.
# Use spdl/io/lib/stubgen.py to generate stubs.




def load_wav(wav_data: bytes, *, time_offset_seconds: float | None = None, duration_seconds: float | None = None) -> dict:
    """
    Extract audio samples from WAV data.

    Args:
        wav_data: Binary WAV data as bytes or string
        time_offset_seconds: Optional starting time in seconds (default: 0.0)
        duration_seconds: Optional duration in seconds (default: until end)

    Returns:
        dict: Dictionary compliant with Array Interface Protocol containing:
            - version: Protocol version (3)
            - shape: Tuple of (num_samples, num_channels)
            - typestr: Data type string
            - data: Tuple of (data_pointer, read_only_flag)
            - owner: Object owning the data buffer

    Raises:
        WAVParseError: If the WAV data is invalid or time range is out of bounds
    """
