#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-strict

"""
Script to generate type stubs for spdl.io.lib nanobind extensions.

This script uses nanobind.stubgen to generate .pyi files for the C++ extension
modules in spdl.io.lib.

Usage:
    python stubgen.py --output-dir /path/to/output
"""

import argparse
from pathlib import Path
from types import ModuleType

from nanobind.stubgen import StubGen
from spdl.io.lib import _archive, _libspdl, _libspdl_cuda, _wav  # pyre-ignore[21]


def generate_stub_content(module: ModuleType) -> str:
    """Generate stub content for a given module.

    Args:
        module_name: Fully qualified module name (e.g., 'spdl.io.lib._spdl_ffmpeg')

    Returns:
        Generated stub content as a string
    """
    print(f"Generating stub for module: {module.__name__}")

    sg = StubGen(module)
    sg.put(module)
    stub_content = sg.get()

    return stub_content


def write_stub_file(stub_content: str, output_dir: Path, output_name: str) -> None:
    """Write stub content to a .pyi file.

    Args:
        stub_content: Generated stub content
        output_dir: Directory where the .pyi file should be written
        output_name: Base name for the output file (without .pyi extension)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / f"{output_name}.pyi"

    header = "\n".join(
        [
            "# Copyright (c) Meta Platforms, Inc. and affiliates.",
            "# All rights reserved.",
            "#",
            "# This source code is licensed under the BSD-style license found in the",
            "# LICENSE file in the root directory of this source tree.",
            "#",
            "# pyre-ignore-all-errors",
            "#",
            "# @"  # intentionally no comma here
            "generated",
            "# This file is generated by stubgen.py",
            "# and should not be edited manually.",
            "# Use spdl/io/lib/stubgen.py to generate stubs.\n\n\n",
        ]
    )

    with open(output_file, "w") as f:
        f.write(header)
        f.write(stub_content)

    print(f"Successfully generated stub: {output_file}")


def run(output_dir: Path) -> None:
    print(f"Output directory: {output_dir}")

    _libspdl._import_once()
    _libspdl_cuda._import_once()

    modules = [
        (_libspdl.module, "_libspdl"),
        (_libspdl_cuda.module, "_libspdl_cuda"),
        (_archive, "_archive"),
        (_wav, "_wav"),
    ]

    for module, output_name in modules:
        stub_content = generate_stub_content(module)
        stub_content = stub_content.replace("_spdl_ffmpeg", "_libspdl")
        write_stub_file(stub_content, output_dir, output_name)

    print("All stubs generated successfully!")


def main(args_: list[str] | None = None) -> None:
    """Main entry point for the stub generation script."""
    parser = argparse.ArgumentParser(
        description="Generate type stubs for spdl.io.lib nanobind extensions."
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        help="Output directory for generated stubs",
        required=True,
        type=Path,
    )

    args = parser.parse_args(args_)
    run(args.output_dir)


if __name__ == "__main__":
    main()
