name: "Build Wheel"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        env:
          SPDL_USE_TRACING: 1
          SPDL_BUILD_STUB: 1
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          set -ex
          uv python pin "${{ inputs.python-version }}"
          uv python list --only-installed
          uv venv
          uv build --all-packages --wheel --directory packaging
          mv ./packaging/dist ~/package

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package
          if-no-files-found: error
          retention-days: 7
          overwrite: true

      - name: Check package
        run: |
          pip install -r ./packaging/requirements.txt
          twine check --strict ~/package/*.whl
