name: Build Conda Package (CPU)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on:  ${{ inputs.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install conda-build
        run: conda install conda-build

      - name: Build SPDL
        run: |
          mkdir ~/package
          conda build \
            ./packaging/conda \
            --python=${{ inputs.python-version }} \
            --output-folder ~/package
      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package
          if-no-files-found: error
          retention-days: 1
          overwrite: true
