name: Build Conda Package (CPU)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      container:
        type: string
        required: false
        default: quay.io/pypa/manylinux_2_34_x86_64
      python-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on:  ${{ inputs.os }}
    container: ${{ inputs.container }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          # For mac
          if ! command -v uv &> /dev/null; then
              curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          set -ex
          cd packaging
          uv python list --only-installed
          uv python pin "${{ inputs.python-version }}"
          uv venv
          ./build_wheels.sh
          mv dist ~/package

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package
          if-no-files-found: error
          retention-days: 7
          overwrite: true

      - name: Check package
        run: |
          /opt/python/cp310-cp310/bin/python -m pip install twine
          /opt/python/cp310-cp310/bin/python -m twine check --strict ~/package/*.whl
