name: Test Wheel (macOS)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  test:
    name: "Unit test (ffmpeg ${{ matrix.ffmpeg-version }})"
    strategy:
      fail-fast: false
      matrix:
        ffmpeg-version: ["5", "6", "7" ]
    runs-on:  macos-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Unit test
        run: |
          pip install $(find "${HOME}/package" -name '*.whl' -depth -maxdepth 1)
          conda install -c conda-forge "ffmpeg==${{ matrix.ffmpeg-version }}"
          conda install -c pytorch numpy pytest pytorch numba
          pytest -v \
              tests/spdl_unittest/io/ \
              tests/spdl_unittest/dataloader/
