name: "Build Docs"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "tests/**"
      - "third_party/**"
      - "README.md"
    branches:
      - main
  push:
    paths-ignore:
      - "tests/**"
      - "third_party/**"
      - "README.md"
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    runs-on:  "${{ matrix.os }}"
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install conda-build
        run: conda install conda-build

      - name: Build package
        run: |
          mkdir ~/package
          conda build ./packaging/conda --python=${{ matrix.python-version }} --output-folder ~/package

      - name: Build docs
        run: |
          conda install -c file://${HOME}/package/ spdl
          conda install -c conda-forge 'ffmpeg==6'
          pip install -r docs/requirements.txt
          ./docs/build.sh
          mv docs/_build _site

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: _site
          if-no-files-found: error
          retention-days: 1
          overwrite: true
