name: Build Conda Package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      run-test:
        type: boolean
        default: false

jobs:
  build:
    name: Build Conda Package
    runs-on:  ${{ inputs.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install conda-build
        run: conda install conda-build

      - name: Build SPDL (CPU)
        run: |
          mkdir ~/package
          conda build \
            ./packaging/conda \
            --python=${{ inputs.python-version }} \
            --output-folder ~/package
      - uses: actions/upload-artifact@v4
        name: Upload artifact (CPU)
        with:
          name: spdl.${{ inputs.os }}.${{ inputs.python-version }}
          path: ~/package
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  unit-test:
    name: Run unit test
    if: ${{ inputs.run-test }}
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        ffmpeg-version: ["5", "6", "7" ]
    runs-on:  ${{ inputs.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          name: spdl.${{ inputs.os }}.${{ inputs.python-version }}
          path: ~/package

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Unit test
        run: |
          conda install -c file://${HOME}/package/ spdl
          conda install -c conda-forge "ffmpeg==${{ matrix.ffmpeg-version}}"
          conda install -c pytorch numpy pytest pytorch numba
          pytest -sv \
              tests/spdl_unittest/io/ \
              tests/spdl_unittest/dataloader/
