name: Build Conda Package

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: "32-core-ubuntu"
      python-version:
        required: true
        type: string
      cu-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install conda-build
        run: conda install conda-build

      - name: Build SPDL
        run: |
          mkdir ~/package
          conda build \
            -c nvidia/label/cuda-${{ inputs.cu-version }} \
            ./packaging/conda \
            --python=${{ inputs.python-version }} \
            --output-folder ~/package
        env:
          CU_VERSION: ${{ inputs.cu-version }}
          CONDA_CUDATOOLKIT_CONSTRAINT: "- nvidia/label/cuda-${{ inputs.cu-version }}::cuda-toolkit"
          CONDA_CUDARUNTIME_CONSTRAINT: "- nvidia/label/cuda-${{ inputs.cu-version }}::cuda-runtime"
          SPDL_USE_CUDA: "1"
          SPDL_USE_NVCODEC: "1"
          SPDL_USE_NVJPEG: "1"
          SPDL_USE_NPPI: "1"
          SPDL_LINK_STATIC_NVJPEG: "0"
          SPDL_USE_TRACING: "1"
          SPDL_BUILD_STUB: "0"

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package
          if-no-files-found: error
          retention-days: 1
          overwrite: true
