name: "Package"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main

jobs:
  #############################################################################
  # macOS
  #############################################################################
  macos-py313:
    name: "macOS 3.13"
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "3.13"
      artifact: wheel-macos-py313

  macos-py312:
    name: "macOS 3.12"
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "3.12"
      artifact: wheel-macos-py312

  macos-py311:
    name: "macOS 3.11"
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "3.11"
      artifact: wheel-macos-py311

  macos-py310:
    name: "macOS 3.10"
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "3.10"
      artifact: wheel-macos-py310

  #----------------------------------------------------------------------------
  # Test
  #----------------------------------------------------------------------------
  macos-py310-test:
    name: "macOS 3.10"
    needs: [ "macos-py310" ]
    uses: ./.github/workflows/_test_macos.yml
    with:
      python-version: "3.10"
      artifact: wheel-macos-py310

  #############################################################################
  # Linux (CPU)
  #############################################################################
  linux-py313:
    name: "Linux 3.13"
    uses: ./.github/workflows/_build_linux.yml
    with:
      python-version: "313"
      artifact: wheel-linux-py313

  linux-py312:
    name: "Linux 3.12"
    uses: ./.github/workflows/_build_linux.yml
    with:
      python-version: "312"
      artifact: wheel-linux-py312

  linux-py311:
    name: "Linux 3.11"
    uses: ./.github/workflows/_build_linux.yml
    with:
      python-version: "311"
      artifact: wheel-linux-py311

  linux-py310:
    name: "Linux 3.10"
    uses: ./.github/workflows/_build_linux.yml
    with:
      python-version: "310"
      artifact: wheel-linux-py310

  #----------------------------------------------------------------------------
  # Test
  #----------------------------------------------------------------------------
  linux-py310-test:
    name: "Linux 3.10"
    needs: [ "linux-py310" ]
    uses: ./.github/workflows/_test_linux.yml
    with:
      python-version: "3.10"
      artifact: wheel-linux-py310

  #############################################################################
  # Linux (CUDA)
  #############################################################################
  linux-py313-cuda12:
    name: "Linux 3.13 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "313"
      artifact: wheel-linux-py313-cuda12
      cuda-version: 12.6

  linux-py312-cuda12:
    name: "Linux 3.12 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "312"
      artifact: wheel-linux-py312-cuda12
      cuda-version: 12.6

  linux-py311-cuda12:
    name: "Linux 3.11 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "311"
      artifact: wheel-linux-py311-cuda12
      cuda-version: 12.6

  linux-py310-cuda12:
    name: "Linux 3.10 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "310"
      artifact: wheel-linux-py310-cuda12
      cuda-version: 12.6

  #----------------------------------------------------------------------------
  # Test
  #----------------------------------------------------------------------------
  linux-py310-cuda12-test:
    name: "Linux 3.10 cu12"
    needs: [ "linux-py310-cuda12" ]
    uses: ./.github/workflows/_test_linux_cuda.yml
    with:
      python-version: "3.10"
      artifact: wheel-linux-py310-cuda12
