name: "Package"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main

jobs:
  #############################################################################
  # Linux (CUDA)
  #############################################################################
  linux-x86-cuda:
    name: "Linux x86_64 CUDA"
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
            cuda-version: "12.6"
            use-nvdec: "nvdec"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      os_build: ubuntu-latest
      os_test: "4-core-ubuntu-gpu-t4"
      container: "pytorch/manylinux2_28-builder:cuda${{ matrix.cuda-version }}"
      arch: x86_64
      python-version: "${{ matrix.python-version }}"
      cuda-version: "${{ matrix.cuda-version }}"
      use-nvdec: "${{ matrix.use-nvdec }}"
      run-test: "${{ matrix.python-version == '3.10'}}"
