name: "Package macOS"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main

jobs:
  #############################################################################
  # Conda
  #############################################################################
  conda-cpu-py312:
    name: "Conda: py3.12"
    uses: ./.github/workflows/conda_cpu_build.yml
    with:
      os: macos-latest
      python-version: "3.12"
      artifact: conda-cpu-py312

  conda-cpu-py311:
    name: "Conda: py3.11"
    uses: ./.github/workflows/conda_cpu_build.yml
    with:
      os: macos-latest
      python-version: "3.11"
      artifact: conda-cpu-py311

  conda-cpu-py310:
    name: "Conda: py3.10"
    uses: ./.github/workflows/conda_cpu_build.yml
    with:
      os: macos-latest
      python-version: "3.10"
      artifact: conda-cpu-py310

  conda-cpu-py310-test:
    name: "Test Conda: py3.10"
    needs: [ "conda-cpu-py310" ]
    uses: ./.github/workflows/conda_cpu_test.yml
    with:
      os: macos-latest
      python-version: "3.10"
      artifact: conda-cpu-py310
