name: "Package"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main

jobs:
  #############################################################################
  # macOS
  #############################################################################
  macos:
    name: "macOS"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "${{ matrix.python-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"

  #############################################################################
  # Linux (CPU)
  #############################################################################
  linux-x86:
    name: "Linux x86_64"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/_build_linux.yml
    with:
      os: ubuntu-latest
      arch: x86_64
      python-version: "${{ matrix.python-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"

  linux-aarch64:
    name: "Linux aarch64"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/_build_linux.yml
    with:
      os: ubuntu-24.04-arm
      arch: aarch64
      python-version: "${{ matrix.python-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"

  #############################################################################
  # Linux (CUDA)
  #############################################################################
  linux-py313-cuda12:
    name: "Linux 3.13 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "313"
      artifact: wheel-linux-py313-cuda12
      cuda-version: 12.6

  linux-py312-cuda12:
    name: "Linux 3.12 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "312"
      artifact: wheel-linux-py312-cuda12
      cuda-version: 12.6

  linux-py311-cuda12:
    name: "Linux 3.11 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "311"
      artifact: wheel-linux-py311-cuda12
      cuda-version: 12.6

  linux-py310-cuda12:
    name: "Linux 3.10 cu12"
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      python-version: "310"
      artifact: wheel-linux-py310-cuda12
      cuda-version: 12.6
      run-test: 'true'
