name: "Package"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "*.md"
    branches:
      - main

jobs:
  #############################################################################
  # macOS
  #############################################################################
  macos:
    name: "macOS"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        free-threaded: [""]
        include:
          - python-version: "3.13"
            free-threaded: "ft"
    uses: ./.github/workflows/_build_macos.yml
    with:
      python-version: "${{ matrix.python-version }}"
      free-threaded: "${{ matrix.free-threaded }}"
      run-test: "${{ matrix.python-version == '3.10' }}"

  #############################################################################
  # Linux (CPU)
  #############################################################################
  linux-x86:
    name: "Linux x86_64"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/_build_linux.yml
    with:
      os: ubuntu-latest
      arch: x86_64
      python-version: "${{ matrix.python-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"

  linux-aarch64:
    name: "Linux aarch64"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/_build_linux.yml
    with:
      os: ubuntu-24.04-arm
      arch: aarch64
      python-version: "${{ matrix.python-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"

  #############################################################################
  # Linux (CUDA)
  #############################################################################
  linux-x86-cuda:
    name: "Linux x86_64 CUDA"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        cuda-version: ["12.6"]
    uses: ./.github/workflows/_build_linux_cuda.yml
    with:
      os_build: ubuntu-latest
      os_test: "4-core-ubuntu-gpu-t4"
      container: "pytorch/manylinux2_28-builder:cuda${{ matrix.cuda-version }}"
      arch: x86_64
      python-version: "${{ matrix.python-version }}"
      cuda-version: "${{ matrix.cuda-version }}"
      run-test: "${{ matrix.python-version == '3.10'}}"
