name: Test Wheel

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: "4-core-ubuntu-gpu-t4"
      python-version:
        required: true
        type: string
      cu-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  unit-test:
    name: "Unit test (ffmpeg ${{ matrix.ffmpeg-version }})"
    strategy:
      fail-fast: false
      matrix:
        ffmpeg-version: ["6"]
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - uses: actions/download-artifact@v4
        with:
          name: "${{ inputs.artifact }}"
          path: ~/package

      - name: Unit test
        run: |
          sudo apt update && sudo apt install -yqq ffmpeg

          ver=${{ inputs.cu-version }}
          ver="${ver//./}"

          pip3 install --find-links "${HOME}/package/" spdl
          pip3 install torch --index-url https://download.pytorch.org/whl/cu${ver}
          pip3 install pytest
          pytest -v tests/spdl_unittest/cuda/
