name: Build Wheel (CUDA)

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: "32-core-ubuntu"
      python-version:
        required: true
        type: string
      cu-version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    container:
      image: pytorch/manylinux2_28-builder:cuda${{ inputs.cu-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build Wheel
        env:
          CUDACXX: "/usr/local/cuda-${{ inputs.cu-version }}/bin/nvcc"
          SPDL_USE_CUDA: "1"
          SPDL_USE_NVCODEC: "1"
          SPDL_USE_NVJPEG: "1"
          SPDL_USE_NPPI: "1"
          SPDL_LINK_STATIC_NVJPEG: "0"
          SPDL_USE_TRACING: "1"
          SPDL_BUILD_STUB: "0"
        run: |
          ver=${{ inputs.python-version }}
          ver="${ver//./}"
          python3 -m pip uninstall -y cmake
          ./packaging/build_wheel.sh "cp${ver}-cp${ver}"
          ./packaging/audit_wheel.sh

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact }}"
          path: ./wheelhouse
          if-no-files-found: error
          retention-days: 1
          overwrite: true
